conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new_user_conversation/<int:receiver_id>/', views.new_user_conversation, name='new_user_conversation'),
    path('new_item_conversation/<int:item_id>/', views.new_item_conversation, name='new_item_conversation'),
    path('user_conversation/<int:pk>/', views.user_conversation_detail, name='user_conversation_detail'),
    path('item_conversation/<int:pk>/', views.item_conversation_detail, name='item_conversation_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('store/', include('store.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('add_item/', views.add_item, name='add_item'),
    path('<int:pk>/edit_item/', views.edit_item, name='edit_item'),
    path('<int:pk>/delete_item/', views.delete_item, name='delete_item'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.view_store, name='view_store'),
]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
]

website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}))
    first_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'First name'}))
    last_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Last name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].label = ''

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db.models import Q

from .forms import SignUpForm
from item.models import Category, Item

def index(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query: 
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'website/index.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })
    
def login_user(request):
    # If user sends POST request, they're done with filling out the form and ready to login
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        # Authenticate
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('website:index')
        else:
            messages.success(
                request, "Either username or password is incorrect. Try again")
            return render(request, 'website/login.html', {})
    # Otherwise, send them the form to login
    else:
        return render(request, 'website/login.html', {})

def logout_user(request):
    logout(request)
    return redirect('website:index')


def signup_user(request):
    # If user sends POST request, they're done with filling out the form and ready to submit
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Login
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('website:index')
    # Otherwise, send them the form to sign up
    else:
        form = SignUpForm()
    return render(request, 'website/signup.html', {'form': form})

website/templates/website/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | GigaStore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <!-- Navbar -->
    {% include 'website/navbar.html' %}

    <!-- Body -->
    <br />
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer class="bg-gray-900 mt-[100px]">
        <div class="w-full max-w-screen-xl mx-auto md:py-8">
            <div class="sm:flex sm:items-center sm:justify-between">
                <a href="/" class="flex items-center mb-4 sm:mb-0">
                    <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">GigaStore</span>
                </a>
                <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-white sm:mb-0 dark:text-gray-400">
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6 ">About</a>
                    </li>
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6 ">Licensing</a>
                    </li>
                    <li>
                        <a href="#" class="hover:underline">Contact</a>
                    </li>
                </ul>
            </div>
            <hr class="my-6 border-white sm:mx-auto lg:my-8" />
            <span class="block text-sm text-gray-500 sm:text-center text-white">© 2023 <a href="/"
                    class="hover:underline">GigaStore</a>. All Rights Reserved.</span>
        </div>
    </footer>
</body>

</html>

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block title %}All{% endblock %}

{% block content %}

<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    {% for item in items %}
    <div class="borderborder-gray-500" style="border-width: 0.2px;">
        <a href="{% url 'item:detail' item.id %}" class="block h-full">
            <div class="h-[270px]">
                <img src="{{ item.image.url }}" class="h-full w-full object-contain" alt="{{ item.name }}">
            </div>

            <div class="p-6 text-center">
                <p class="text-sm lg:text-md font-medium">{{ item.name }}</p>
                <p class="text-gray-500 text-xs lg:text-sm">$ {{ item.price }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h1 class="mb-6 text-4xl bold">Login</h1>
    <br />

    <form method="POST" action="{% url 'website:login' %}">
        {% csrf_token %}

        {% if messages %}
        {% for message in messages %}
        <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert">
            <svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                fill="currentColor" viewBox="0 0 20 20">
                <path
                    d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
            </svg>
            <span class="sr-only">Info</span>
            <div>
                {{message}}
            </div>
        </div>
        {% endfor %}
        {% endif %}

        <div class="mb-3">
            <input type="text" class="form-control" name="username" placeholder="Username" required>
        </div>

        <div class="mb-3">
            <input type="password" class="form-control" name="password" placeholder="Password" required>
        </div>

        <br />
        <button type="submit" class="px-4 py-2 font-medium text-white bg-gray-500 rounded-md hover:bg-gray-600">
            Login
        </button>

    </form>
</div>

{% endblock %}

website/templates/website/navbar.html
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-[#131a22] flex justify-between items-center px-4">
        <div class="container-fluid">
            <!-- Logo -->
            <div class="flex-shrink-0">
                <a class="navbar-brand " href="{% url 'website:index' %}">GigaStore</a>
            </div>

            <!-- Browse -->
            <form class="d-flex flex-grow text-center ml-[20%] mr-[20%]" role="search">
                <div class="input-group">
                    <!-- <div class="dropdown">
                    <button class="btn bg-[#febd69] dropdown-toggle" type="button" id="categoryDropdown"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Select Category
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="categoryDropdown">
                        <li><a class="dropdown-item" href="#">Category 1</a></li>
                        <li><a class="dropdown-item" href="#">Category 2</a></li>
                        <li><a class="dropdown-item" href="#">Category 3</a></li>
                    </ul>
                </div> -->

                    <form method="get" action="/login">
                        <input name="query" class="form-control" type="text" value="{{query}}" placeholder="Search"
                            aria-label="Search">
                        <button class="btn bg-[#febd69] hover:bg-[#faab46]" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="black" class="text-white w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                            </svg>
                        </button>
                    </form>
                </div>
            </form>


            <!-- Links -->
            <div class=" flex-shrink-0" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:index' %}">My Store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'item:add_item' %}">Add Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'conversation:inbox' %}">Inbox</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:logout' %}">Logout</a>
                    </li>
                    {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:login' %}">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:signup' %}">Sign up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="bg-[#232f3e] flex  px-4">
        {% for category in categories %}
        <a href="{% url 'website:index' %}?query={{ query }}&category={{ category.id }}">
            <div class="text-white text-sm p-2 mx-2">
                {{ category.name }}
            </div>
        </a>
        {% endfor %}
    </div>
</div>

website/templates/website/signup.html
{% extends 'website/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h1 class="mb-6 text-4xl bold">Sign up</h1>
    <br />

    <form method="POST" action="">
        {% csrf_token %}

        {% if form.errors %}


        <div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert">
            <svg class="flex-shrink-0 inline w-4 h-4 mr-3 mt-[2px]" aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path
                    d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
            </svg>
            <span class="sr-only">Danger</span>
            <div>
                <span class="font-medium">Your form has the following errors: </span>
                <ul class="mt-1.5 ml-4 list-disc list-outside">
                    {% for field in form %}
                    {% if field.errors %}
                    <li>{{ field.errors }}</li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>

        {% endif %}

        <div class="form">
            <div class="mb-3">
                {{ form.username }}
                <span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and
                        @/./+/-/_
                        only.</small></span>
            </div>

            <div class="mb-3">
                {{ form.first_name }}
            </div>

            <div class="mb-3">
                {{ form.last_name }}
            </div>

            <div class="mb-3">
                {{ form.email }}
            </div>

            <div class="mb-3">
                {{ form.password1 }}
                <ul class="form-text text-muted small list-disc pl-8 mt-3">
                    <li>Your password can't be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can't be a commonly used password.</li>
                    <li>Your password can't be entirely numeric.</li>
                </ul>
            </div>


            <div class="mb-3">
                {{ form.password2 }}
                <span class="form-text text-muted"><small>Enter the same password as before, for
                        verification.</small></span>
            </div>
        </div>

        <br />
        <button type="submit" class="px-4 py-2 font-medium text-white bg-gray-500 rounded-md hover:bg-gray-600">
            Sign Up
        </button>
    </form>
    {% endblock %}