conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new_user_conversation/<int:receiver_id>/', views.new_user_conversation, name='new_user_conversation'),
    path('new_item_conversation/<int:item_id>/', views.new_item_conversation, name='new_item_conversation'),
    path('user_conversation/<int:pk>/', views.user_conversation_detail, name='user_conversation_detail'),
    path('item_conversation/<int:pk>/', views.item_conversation_detail, name='item_conversation_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('store/', include('store.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('add_item/', views.add_item, name='add_item'),
    path('<int:pk>/edit_item/', views.edit_item, name='edit_item'),
    path('<int:pk>/delete_item/', views.delete_item, name='delete_item'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.view_store, name='view_store'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=225)

    class Meta: 
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_new = models.BooleanField(default=False)
    image = models.ImageField(upload_to="images", blank=True, null=True)
    seller = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_sold = models.BooleanField(default=False)
    # likes
    # comments
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from .models import Item 

INPUT_CLASSES = 'w-full p-2 border border-gray-700 rounded-md'


class AddItemForm(forms.ModelForm):
    
    class Meta: 
        model = Item
        fields = ( 'name', 'category','description', 'price','is_new', 'image', 'quantity')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class':  'w-[200px] p-2 border border-gray-700 rounded-md'
            }),
            'image': forms.FileInput(attrs={
                'class': ''
            }),
            'quantity': forms.TextInput(attrs={
                'class': 'w-[200px] p-2 border border-gray-700 rounded-md'
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'category','description', 'price','is_new', 'image', 'quantity')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class':  'w-[200px] p-2 border border-gray-700 rounded-md'
            }),
            'image': forms.FileInput(attrs={
                'class': ''
            }),
            'quantity': forms.TextInput(attrs={
                'class': 'w-[200px] p-2 border border-gray-700 rounded-md'
            }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile

from .models import Item, Category
from .forms import AddItemForm, EditItemForm

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

@login_required
def add_item(request):
    if request.method == 'POST':
        form = AddItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.seller = request.user      # to make sure that you are the owner of the item, and only you can update/delete it
            if not item.image:
                default_image_content = 'no images'  
                item.image.save('armchair.jpeg', ContentFile(default_image_content), save=False)
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = AddItemForm()

    return render(request, 'item/add_item.html', {
        'form': form,
        'action': 'add',
    })

@login_required
def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk, seller=request.user)  # we have to pass in seller to make sure that only the owner of the product can edit it. If you're logged in as a user but you are not the owner, you can't edit the product

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/add_item.html', {
        'form': form,
        'action': 'edit',
    })

@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk, seller=request.user)
    item.delete()

    return redirect('store:index')

item/templates/item/add_item.html
{% extends 'website/base.html' %}

{% block title %}Add item{% endblock %}

{% block content %}

<div class="col-md-6 offset-md-3">

    <h1 class="mb-6 text-3xl">Add new item to your store</h1>
    <br />

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.errors or form.non_field_errors %}

        <div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert">
            <svg class="flex-shrink-0 inline w-4 h-4 mr-3 mt-[2px]" aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path
                    d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
            </svg>
            <span class="sr-only">Danger</span>
            <div>
                <span class="font-medium">Your form has the following errors: </span>
                <ul class="mt-1.5 ml-4 list-disc list-outside">
                    {% for field in form %}
                    {% if field.errors %}
                    <li>{{field}}{{ field.errors }}</li>
                    {% endif %}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </ul>
            </div>
        </div>

        {% endif %}

        <div class="form">
            {% for field in form %}
            <div>
                <div>{{field.label}}</div>
                <div class="mb-3">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
        </div>

        <br />

        <button type="submit" class="px-4 py-2 font-medium text-white bg-gray-500 rounded-md hover:bg-gray-600">
            {% if action == 'add' %}
            Add
            {% else %}
            Edit
            {% endif %}
        </button>
    </form>

</div>
{% endblock %}

item/templates/item/detail.html
{% extends 'website/base.html' %}

{% block title %}{{item.name}}{% endblock %}

{% block content %}

<div class="container">
    <div class="grid grid-cols-12">
        <div class="col-span-1"></div>
        <div class="col-span-5">
            <img src="{{ item.image.url }}" class="h-full w-full object-fill">
        </div>
        <div class="col-span-6 p-10  bg-[#dbf4ff]">
            <!-- Seller -->
            <div class="flex gap-3 mb-6">
                <a href="{% url 'store:view_store' item.seller.id %}">
                    <div class="flex gap-3">
                        <div
                            class="w-10 h-10 flex items-center justify-center rounded-full border border-gray-300 bg-[#2e708c] text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                            </svg>
                        </div>
                        <div>{{item.seller.username}}</div>
                    </div>
                </a>
                <a href="{% url 'conversation:new_user_conversation' item.seller.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="#2e708c" class="w-[20px] h-[20px] mt-1">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                    </svg>
                </a>
            </div>


            <!-- Item info -->
            <div class="flex flex-col gap-2">
                <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
                {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong>
                    {{ item.description }}
                </p>
                {% endif %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Price:</strong>
                    $ {{ item.price }}
                </p>
                <p class="text-gray-700">
                    <strong class="text-gray-500">Condition:</strong>
                    {% if item.is_new %}
                    New
                    {% else %}
                    Pre-owned
                    {% endif %}
                </p>
                <p class="text-gray-700">
                    <strong class="text-gray-500">Quantity:</strong>
                    {{item.quantity}}
                </p>
            </div>

            <!-- Buttons -->
            <div class="mt-[100px] flex gap-4">
                {% if request.user == item.seller %}

                <!-- Edit, Delete buttons -->
                <div class="flex gap-4">
                    <a href="{% url 'item:edit_item' item.id %}" title="Edit">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" style="width: 30px; height: 30px;"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="#1b5066" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </a>
                    <a href="{% url 'item:delete_item' item.id %}" title="Delete">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" style="width: 30px; height: 30px;"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="#FF0000" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                        </svg>
                    </a>
                </div>

                {% else %}
                <a href="#"
                    class="flex px-8 py-2.5 items-center justify-center  bg-[#42abed] text-white rounded-sm ">Add
                    to cart</a>
                <a href="{% url 'conversation:new_item_conversation' item.id %}"
                    class="flex  px-8 py-2.5 items-center justify-center text-[#42abed] bg-white rounded-sm"
                    style=" border: 1px solid #42abed;">Contact
                    seller</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="w-full bg-gray-200 h-[1px] mt-[100px]"></div>

    <div class="mt-[20px]">

        <div class="text-center text-lg font-medium">RELATED ITEMS</div>
        <div class="grid grid-cols-6 mt-4">
            {% for item in related_items %}
            <div class="borderborder-gray-500" style="border-width: 0.2px;">
                <a href="{% url 'item:detail' item.id %}" class="block h-full">
                    <div class="h-[150px]">
                        <img src="{{ item.image.url }}" class="h-full w-full object-contain" alt="{{ item.name }}">
                    </div>

                    <div class="px-6 py-4 text-center">
                        <p class="text-sm font-medium">{{ item.name }}</p>
                        <p class="text-gray-500 text-xs">$ {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}